version: '3.8'
services:

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: simya
      MYSQL_USER: simya
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234

  redis:
    image: redis
    ports:
      - "6379:6379"